version: '3'

services:

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service-multistep.dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      AUTH_BASE_URL: "http://authentication-service"

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: unless-stopped
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgresdb port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  postgresdb:
    image: "postgres:14.2"
    ports:
      - "55432:5432"
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/